name: Runner Info

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Show runner OS
        run: uname -a
