name: Matrix Build Demo
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ["Mahmud","Hasan"]
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo Hello! ${{ matrix.name }}
